# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hftokenizers_wrappers", use_symbols = TRUE, package_name = "hftokenizers")

#' @docType package
#' @usage NULL
#' @useDynLib hftokenizers, .registration = TRUE
NULL

RTokenizer <- new.env(parent = emptyenv())

RTokenizer$from_model <- function(model) .Call(wrap__RTokenizer__from_model, model)

RTokenizer$train <- function(files, trainer) invisible(.Call(wrap__RTokenizer__train, self, files, trainer))

RTokenizer$encode <- function(sequence, pair, is_pretokenized, add_special_tokens) .Call(wrap__RTokenizer__encode, self, sequence, pair, is_pretokenized, add_special_tokens)

RTokenizer$decode <- function(ids, skip_special_tokens) .Call(wrap__RTokenizer__decode, self, ids, skip_special_tokens)

RTokenizer$get_vocab <- function(with_added_tokens) .Call(wrap__RTokenizer__get_vocab, self, with_added_tokens)

RTokenizer$get_pre_tokenizer <- function() .Call(wrap__RTokenizer__get_pre_tokenizer, self)

RTokenizer$set_pre_tokenizer <- function(pre_tokenizer) invisible(.Call(wrap__RTokenizer__set_pre_tokenizer, self, pre_tokenizer))

RTokenizer$get_post_processor <- function() .Call(wrap__RTokenizer__get_post_processor, self)

RTokenizer$set_post_processor <- function(post_processor) invisible(.Call(wrap__RTokenizer__set_post_processor, self, post_processor))

RTokenizer$save <- function(path, pretty) invisible(.Call(wrap__RTokenizer__save, self, path, pretty))

RTokenizer$from_file <- function(path) .Call(wrap__RTokenizer__from_file, path)

RTokenizer$token_to_id <- function(token) .Call(wrap__RTokenizer__token_to_id, self, token)

#' @export
`$.RTokenizer` <- function (self, name) { func <- RTokenizer[[name]]; environment(func) <- environment(); func }

RModel <- new.env(parent = emptyenv())

RModel$get_trainer <- function() .Call(wrap__RModel__get_trainer, self)

RModel$save <- function(folder, prefix) .Call(wrap__RModel__save, self, folder, prefix)

#' @export
`$.RModel` <- function (self, name) { func <- RModel[[name]]; environment(func) <- environment(); func }

RModelsBpe <- new.env(parent = emptyenv())

RModelsBpe$new <- function(vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk) .Call(wrap__RModelsBpe__new, vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk)

RModelsBpe$read_file <- function(vocab, merges) .Call(wrap__RModelsBpe__read_file, vocab, merges)

RModelsBpe$from_file <- function(vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk) .Call(wrap__RModelsBpe__from_file, vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk)

#' @export
`$.RModelsBpe` <- function (self, name) { func <- RModelsBpe[[name]]; environment(func) <- environment(); func }

RNormalizer <- new.env(parent = emptyenv())

#' @export
`$.RNormalizer` <- function (self, name) { func <- RNormalizer[[name]]; environment(func) <- environment(); func }

RPreTokenizer <- new.env(parent = emptyenv())

#' @export
`$.RPreTokenizer` <- function (self, name) { func <- RPreTokenizer[[name]]; environment(func) <- environment(); func }

RWhitespace <- new.env(parent = emptyenv())

RWhitespace$new <- function() .Call(wrap__RWhitespace__new)

#' @export
`$.RWhitespace` <- function (self, name) { func <- RWhitespace[[name]]; environment(func) <- environment(); func }

RPostProcessor <- new.env(parent = emptyenv())

RPostProcessor$process <- function(encoding, pair_encoding, add_special_tokens) .Call(wrap__RPostProcessor__process, self, encoding, pair_encoding, add_special_tokens)

#' @export
`$.RPostProcessor` <- function (self, name) { func <- RPostProcessor[[name]]; environment(func) <- environment(); func }

RSpecialToken <- new.env(parent = emptyenv())

#' @export
`$.RSpecialToken` <- function (self, name) { func <- RSpecialToken[[name]]; environment(func) <- environment(); func }

VecRSpecialToken <- new.env(parent = emptyenv())

#' @export
`$.VecRSpecialToken` <- function (self, name) { func <- VecRSpecialToken[[name]]; environment(func) <- environment(); func }

RTemplateProcessing <- new.env(parent = emptyenv())

RTemplateProcessing$new <- function(single, pair, special_tokens) .Call(wrap__RTemplateProcessing__new, single, pair, special_tokens)

#' @export
`$.RTemplateProcessing` <- function (self, name) { func <- RTemplateProcessing[[name]]; environment(func) <- environment(); func }

RDecoder <- new.env(parent = emptyenv())

#' @export
`$.RDecoder` <- function (self, name) { func <- RDecoder[[name]]; environment(func) <- environment(); func }

#' @export
REncoding <- new.env(parent = emptyenv())

REncoding$get_n_sequences <- function() .Call(wrap__REncoding__get_n_sequences, self)

REncoding$set_sequence_id <- function(sequence_id) invisible(.Call(wrap__REncoding__set_sequence_id, self, sequence_id))

REncoding$get_ids <- function() .Call(wrap__REncoding__get_ids, self)

REncoding$get_tokens <- function() .Call(wrap__REncoding__get_tokens, self)

REncoding$get_word_ids <- function() .Call(wrap__REncoding__get_word_ids, self)

REncoding$get_sequence_ids <- function() .Call(wrap__REncoding__get_sequence_ids, self)

REncoding$get_type_ids <- function() .Call(wrap__REncoding__get_type_ids, self)

REncoding$get_offsets <- function() .Call(wrap__REncoding__get_offsets, self)

REncoding$get_special_tokens_mask <- function() .Call(wrap__REncoding__get_special_tokens_mask, self)

REncoding$get_attention_mask <- function() .Call(wrap__REncoding__get_attention_mask, self)

REncoding$token_to_word <- function(token_index) .Call(wrap__REncoding__token_to_word, self, token_index)

REncoding$char_to_token <- function(char_pos, sequence_index) .Call(wrap__REncoding__char_to_token, self, char_pos, sequence_index)

REncoding$char_to_word <- function(char_pos, sequence_index) .Call(wrap__REncoding__char_to_word, self, char_pos, sequence_index)

REncoding$truncate <- function(max_length, stride) .Call(wrap__REncoding__truncate, self, max_length, stride)

#' @rdname REncoding
#' @usage NULL
#' @export
`$.REncoding` <- function (self, name) { func <- REncoding[[name]]; environment(func) <- environment(); func }

RBpeTrainer <- new.env(parent = emptyenv())

RBpeTrainer$new <- function(vocab_size, min_frequency, show_progress, special_tokens, limit_alphabet, initial_alphabet, continuing_subword_prefix, end_of_word_suffix) .Call(wrap__RBpeTrainer__new, vocab_size, min_frequency, show_progress, special_tokens, limit_alphabet, initial_alphabet, continuing_subword_prefix, end_of_word_suffix)

#' @export
`$.RBpeTrainer` <- function (self, name) { func <- RBpeTrainer[[name]]; environment(func) <- environment(); func }

