# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hftokenizers_wrappers", use_symbols = TRUE, package_name = "hftokenizers")

#' @docType package
#' @usage NULL
#' @useDynLib hftokenizers, .registration = TRUE
NULL

RTokenizer <- new.env(parent = emptyenv())

RTokenizer$from_model <- function(model) .Call(wrap__RTokenizer__from_model, model)

RTokenizer$train <- function(files) invisible(.Call(wrap__RTokenizer__train, self, files))

RTokenizer$encode <- function(sequence, pair, is_pretokenized, add_special_tokens) .Call(wrap__RTokenizer__encode, self, sequence, pair, is_pretokenized, add_special_tokens)

RTokenizer$decode <- function(ids, skip_special_tokens) .Call(wrap__RTokenizer__decode, self, ids, skip_special_tokens)

RTokenizer$get_vocab <- function(with_added_tokens) .Call(wrap__RTokenizer__get_vocab, self, with_added_tokens)

`$.RTokenizer` <- function (self, name) { func <- RTokenizer[[name]]; environment(func) <- environment(); func }

RModel <- new.env(parent = emptyenv())

RModel$get_trainer <- function() .Call(wrap__RModel__get_trainer, self)

RModel$save <- function(folder, prefix) .Call(wrap__RModel__save, self, folder, prefix)

`$.RModel` <- function (self, name) { func <- RModel[[name]]; environment(func) <- environment(); func }

RModelsBpe <- new.env(parent = emptyenv())

RModelsBpe$new <- function(vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk) .Call(wrap__RModelsBpe__new, vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk)

RModelsBpe$read_file <- function(vocab, merges) .Call(wrap__RModelsBpe__read_file, vocab, merges)

RModelsBpe$from_file <- function(vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk) .Call(wrap__RModelsBpe__from_file, vocab, merges, cache_capacity, dropout, unk_token, continuing_subword_prefix, end_of_word_suffix, fuse_unk)

`$.RModelsBpe` <- function (self, name) { func <- RModelsBpe[[name]]; environment(func) <- environment(); func }

RNormalizer <- new.env(parent = emptyenv())

`$.RNormalizer` <- function (self, name) { func <- RNormalizer[[name]]; environment(func) <- environment(); func }

RPreTokenizer <- new.env(parent = emptyenv())

`$.RPreTokenizer` <- function (self, name) { func <- RPreTokenizer[[name]]; environment(func) <- environment(); func }

RPostProcessor <- new.env(parent = emptyenv())

`$.RPostProcessor` <- function (self, name) { func <- RPostProcessor[[name]]; environment(func) <- environment(); func }

RDecoder <- new.env(parent = emptyenv())

`$.RDecoder` <- function (self, name) { func <- RDecoder[[name]]; environment(func) <- environment(); func }

REncoding <- new.env(parent = emptyenv())

REncoding$get_n_sequences <- function() .Call(wrap__REncoding__get_n_sequences, self)

REncoding$set_sequence_id <- function(sequence_id) invisible(.Call(wrap__REncoding__set_sequence_id, self, sequence_id))

REncoding$get_ids <- function() .Call(wrap__REncoding__get_ids, self)

REncoding$get_tokens <- function() .Call(wrap__REncoding__get_tokens, self)

REncoding$get_word_ids <- function() .Call(wrap__REncoding__get_word_ids, self)

REncoding$get_sequence_ids <- function() .Call(wrap__REncoding__get_sequence_ids, self)

REncoding$get_type_ids <- function() .Call(wrap__REncoding__get_type_ids, self)

REncoding$get_special_tokens_mask <- function() .Call(wrap__REncoding__get_special_tokens_mask, self)

REncoding$get_attention_mask <- function() .Call(wrap__REncoding__get_attention_mask, self)

REncoding$token_to_word <- function(token_index) .Call(wrap__REncoding__token_to_word, self, token_index)

REncoding$char_to_token <- function(char_pos, sequence_index) .Call(wrap__REncoding__char_to_token, self, char_pos, sequence_index)

REncoding$char_to_word <- function(char_pos, sequence_index) .Call(wrap__REncoding__char_to_word, self, char_pos, sequence_index)

REncoding$truncate <- function(max_length, stride) .Call(wrap__REncoding__truncate, self, max_length, stride)

`$.REncoding` <- function (self, name) { func <- REncoding[[name]]; environment(func) <- environment(); func }

